version: "3.8"

services:
  portfolio-app:
    container_name: portfolio-app
    image: portfolio-app
    ports: 
      - 80:80
    build: .
  generator-app:
    container_name: generator-app
    image: generator-app
    build: ../react-small-projects/generator/