version: "3.8"

services:
  portfolio-app:
    container_name: portfolio-app
    image: portfolio-app
    ports:
      - 80:80
    build: .
  generator-app:
    container_name: generator-app
    image: generator-app
    build: ../react-small-projects/generator/
  tenzies-app:
    container_name: tenzies-app
    image: tenzies-app
    build: ../react-small-projects/tenzies/
  factorial-app:
    container_name: factorial-app
    image: factorial-app
    build: ../exercises/factorial/
  palindrome-app:
    container_name: palindrome-app
    image: palindrome-app
    build: ../exercises/palindrome/
  unit-converter-app:
    container_name: unit-converter-app
    image: unit-converter-app
    build: ../exercises/unit-converter/
  cash-register-app:
    container_name: cash-register-app
    image: cash-register-app
    build: ../exercises/cash-register/
  phone-check-app:
    container_name: phone-check-app
    image: phone-check-app
    build: ../exercises/phone-check/
  restaurant:
    container_name: restaurant
    image: restaurant
    build: ../restaurant/
  landing-page:
    container_name: landing-page
    image: landing-page
    build: ../landing-page/
  landing-page:
    container_name: money-tracker-app
    image: money-tracker-app
    build: ../money-tracker-app/