version: "3.8"

services:
  portfolio-app:
    container_name: portfolio-app
    image: portfolio-app
    ports:
      - 80:80
    build: .
  generator-app:
    container_name: generator-app
    image: generator-app
    build: ../react-small-projects/generator/
  tenzies-app:
    container_name: tenzies-app
    image: tenzies-app
    build: ../react-small-projects/tenzies/
  got-api-app:
    container_name: got-api-app
    image: got-api-app
    build: ../got-app-api
  
