export default function Experience() {
    return (
    <div className="experience-container">
        <ul>FREELANCE DEVELOPER
            <li>BUILDING WEBSITES FROM SCRATCH, USING SEMANTIC ELEMENTS AND "MOBILE FIRST" APPROACH. PLANNING THEIR STRUCTURE AND DESIGN</li>
            <li>CREATING REACT COMPONENTS, DUMB COMPONENTS AND USING HOOKS</li>
            <li>TROUBLESHOOTING PROBLEMS WITH JAVASCRIPT LOGIC AND REFINING PIXEL PERFECT STYLES</li>
            <li>WRITING UNIT TESTS (JEST) </li>
            <li>CREATING ANIMATIONS USING CSS ANIMATIONS AND KEYFRAMES</li>
            <li>CONFIGURING VPS SERVERS AND DOCKERIZED APPS WITH DOCKER-COMPOSE</li>
        </ul>
    </div>
    )
}